### PR TITLE
Added support for specifying properties and relationships at runtime

### PR DESCRIPTION
**Pull request by jparks1**

### CODE REVIEW

**Comment by jacek-gorgon** [comment]
Thanks for contributing!
Is there a specific reason you need the methods that take in strings (as opposed to lambdas, which is already supported)?

So instead of typing:
`builder
.WithSimpleProperty(x => x.Foo)
.WithSimpleProperty(x => x.Bar)`
you need to be able to specify:
`builder.WithSpecifiedSimpleProperties(new [] { "Foo", "Bar" })`

**Comment by jparks1** [comment]
We need a way to define the properties to include in the output document at runtime from a comma delimited string passed into the controller. We also need the same type of support for relationships. The goal is to implement the fields and include parameters of the JSONAPI spec. Any other suggestions you may have are very much appreciated.

**Comment by jacek-gorgon** [comment]
Unfortunately, this code won't do what you need. It applies the filtering to the global configuration and not per-request.

While I was off for a while, I'm comming back to coding now. I've already started work on supplying an optional Context instance into controller methods. This would hold a clone of the configuration with the potential for modifying behavior per request. This needs some more work and is part of actually bringing up creating/updating to 1.0 standard.

If you want to help, modify this code to work on a Configuration and ResourceMapping instances, as this will be mergeable with the code base once I'm done. Those types also already have useful dictionaries so you don't need to do any actual reflection (which shouldn't happen on every request).

**Comment by jparks1** [comment]
I’m not sure  I understand the implementation. Can you give me an example at the action level where I can dynamically define the fields and relationships I want mapped?

**Comment by jparks1** [comment]
Jacek, is there any way to dynamically configure resources without using a generic type? We are trying to make this library somewhat generic to be used with many model objects but are having trouble because the Resource configuration requires that the type be passed in as a generic type and we need to support multiple Resource configurations depending on the microservice the library is getting used in.

For example, If we have a World object, we also need to define a Continent, and Country, and City, etc. We are trying to avoid having to hard code the configuration and make it reusable.

Thanks
John

**Pull request closed without merging**
